/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/yoda.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.CABEZA_5_CABEZA_5_0.geometry} material={materials.CABEZA_5} />
          <mesh geometry={nodes.Ropa_3_Ropa_3_0.geometry} material={materials.Ropa_3} />
          <mesh geometry={nodes.MANGAS_1_MANGAS_1_0.geometry} material={materials.MANGAS_1} />
          <mesh geometry={nodes.MANO_1_MANO_1_0.geometry} material={materials.MANO_1} />
          <mesh geometry={nodes.MANO_3_MANO_3_0.geometry} material={materials.MANO_3} />
          <mesh geometry={nodes.OJO_1_1_OJO_1_1_0.geometry} material={materials.OJO_1_1} />
          <mesh geometry={nodes.OJO_1_2_OJO_1_2_0.geometry} material={materials.OJO_1_2} />
          <mesh geometry={nodes._CUELLO_1__CUELLO_1_0.geometry} material={materials.CUELLO_1} />
          <mesh geometry={nodes.CUELLO_2_1_CUELLO_2_1_0.geometry} material={materials.CUELLO_2_1} />
          <mesh geometry={nodes.Fibers33_Fibers33_0.geometry} material={materials.Fibers33} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/yoda.glb')
